apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/cluster-proxy-addon?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "backplane-2.6"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: release-mce-26
    appstudio.openshift.io/component: cluster-proxy-addon-mce-26
    pipelines.appstudio.openshift.io/type: build
  name: cluster-proxy-addon-mce-26-on-push
  namespace: crt-redhat-acm-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-proxy-addon-mce-26:{{revision}}
  - name: dockerfile
    value: Dockerfile.rhtap
  - name: path-context
    value: .
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/arm64
    - linux/ppc64le
    - linux/s390x
  - name: send-slack-notification
    value: "true"
  - name: konflux-application-name
    value: "release-mce-26"
  - name: slack-member-id
    value: "U01TX25RJ3B"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/stolostron/konflux-build-catalog.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/common.yaml

  taskRunTemplate:
    serviceAccountName: build-pipeline-cluster-proxy-addon-mce-26
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
